# Generated by Django 4.0.3 on 2023-08-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tag', models.IntegerField()),
                ('cover_path', models.TextField(blank=True)),
                ('score', models.IntegerField(blank=True)),
                ('memo', models.TextField(blank=True)),
                ('liked', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RecordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.user')),
                ('record_id', models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, related_name='record', to='api.record')),
            ],
        ),
    ]
