# Generated by Django 4.0.3 on 2023-08-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_record_recordlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordList',
            new_name='Record_List',
        ),
    ]
