# Generated by Django 4.0.3 on 2023-08-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_recordlist_record_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('memo', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record_list',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='record_owner', to='api.user'),
        ),
        migrations.CreateModel(
            name='Wish_Media_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='wish_owner', to='api.user')),
                ('wish_id', models.ForeignKey(db_column='wish_id', on_delete=django.db.models.deletion.CASCADE, related_name='wish_media', to='api.wish_media')),
            ],
        ),
    ]
