# Generated by Django 4.0.3 on 2023-09-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wish_media_alter_record_date_alter_record_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='cover_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
