# Generated by Django 4.0.3 on 2023-09-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_record_cover_path_alter_record_memo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='liked',
            field=models.BooleanField(default=0),
        ),
    ]
