# Generated by Django 4.0.3 on 2023-09-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_record_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish_media',
            name='tag',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
